### ISSUE TITLE
Add support for creating Int64 columns

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/migrator#14]

**Comment by mikeeus** [comment]
I noticed you already have the column_type method map Int64 to 'bigint', and it worked fine when I tested it.
```
def column_type(type : Int64.class)
    "bigint"
end
```
What's needed to complete this feature?

Also what do you think about using bigserial for the id property, or maybe adding an option to CreateTableStatement to allow it. Something like:

```
LuckyMigrator::CreateTableStatement.new(:users, bigserial: true)
```

**Comment by paulcsmith** [comment]
I think this feature is done I just haven't closed it. Oops :)

**Comment by paulcsmith** [comment]
Oh and I think biserial should be the default actually. I would just need to coordinate changes with LuckyRecord so it uses Int64. Thanks for suggesting the idea!

**Comment by mikeeus** [comment]
Awesome! let me know if you need me to do anything one this

**Comment by paulcsmith** [comment]
Will do. Thank you so much @mikeeus. I think I'm going to hold off on this one for now until I have more time to update the guides and other stuff. But I'll ping you when this is ready. I'm going to add a "help wanted" to some other issues. If you have time I'd love it if you could take a look!

**Comment by mikeeus** [comment]
Absolutely, I'll keep an eye out! I'm excited to use Crystal and would love to see lucky become full featured, because I have an app I want to build with it. So I'm happy to help in any way I can.
