### ISSUE TITLE
Use timestamptz as default

### ISSUE THREAD

**Issue by mikeeus** [luckyframework/migrator#19]
What do you think about the migration use timestamptz as the default column type for Time?[http://justatheory.com/computers/databases/postgresql/use-timestamptz.html](url)

**Comment by paulcsmith** [comment]
That is definitely a good idea. Not sure why I didn't do that at first. Thanks for the suggestion!

**Comment by paulcsmith** [comment]
Oh and default timezone should be UTC

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/migrator/pull/24
