### ISSUE TITLE
Add DSL for creating indices outside of create/alter

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/migrator#6]
#17 addresses adding indices when the column is created, but we also need something for adding them after the fact in `alter` or outside of `alter`

```crystal
create users do
  # This is done and in master
  add email, unique: true
end

# But we need to be able to create them outside of a create/alter block
create_index :email, on: :users, unique: true
create_index :some_id, on: :users
```

**Comment by mikeeus** [comment]
I think this is closed by #29, except it might be better to rename `add_index` to `create_index`. But the functionality is the same

**Comment by paulcsmith** [comment]
Yes you're right it is closed by that. Good catch. Also, yes I think it should be renamed. I'll create an issue

**Comment by mikeeus** [comment]
K I made a PR for it
